# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Install dependencies
      run: |
        cd ~/wooseong/Autotrade-bot
        git pull
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Restart python
      shell: bash
      run: |
        kill -9 $(ps -ef | grep Autotrade.py | awk '{print $2}')
      env:
        CI: "" 
    - name : print log
      run: |
        cd ~/wooseong/Autotrade-bot
        nohup python3 Autotrade.py &  > upbit.log 
        cd ~/wooseong/Autotrade-bot
        cat upbit.log
